In [11]:
'''
Variables
    There are 14 attributes in each case of the dataset. They are:

        CRIM - per capita crime rate by town
        ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
        INDUS - proportion of non-retail business acres per town.
        CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
        NOX - nitric oxides concentration (parts per 10 million)
        RM - average number of rooms per dwelling
        AGE - proportion of owner-occupied units built prior to 1940
        DIS - weighted distances to five Boston employment centres
        RAD - index of accessibility to radial highways
        TAX - full-value property-tax rate per $10,000
        PTRATIO - pupil-teacher ratio by town
        B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
        LSTAT - % lower status of the population

        MEDV - Median value of owner-occupied homes in $1000's
'''
''

''

In [12]:
import keras
from keras.layers import *
from keras.optimizers import *
from keras.models import Model, Sequential
from keras.utils import np_utils
from keras.utils import plot_model

import numpy as np
import pandas as pd

import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

print(keras.__version__)
print(tf.__version__)

2.2.0
1.8.0


In [44]:
from keras.datasets import boston_housing

(X_train, Y_train), (X_test, Y_test) = boston_housing.load_data()
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(404, 13) (404,)
(102, 13) (102,)


In [45]:
X_train[0], Y_train[0]

(array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
         91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
         18.72   ]), 15.2)

In [46]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
X_train[0], Y_train[0]

(array([-0.27224633, -0.48361547, -0.43576161, -0.25683275, -0.1652266 ,
        -0.1764426 ,  0.81306188,  0.1166983 , -0.62624905, -0.59517003,
         1.14850044,  0.44807713,  0.8252202 ]), 15.2)

In [85]:
# Create model
model = Sequential()
model.add(Dense(13, input_dim=13, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='linear'))

# Compile model
model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics=['mean_absolute_error'])
model.summary()

# Save model image
plot_model(model, to_file='regression-boston.png')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_67 (Dense)             (None, 13)                182       
_________________________________________________________________
dense_68 (Dense)             (None, 6)                 84        
_________________________________________________________________
dense_69 (Dense)             (None, 1)                 7         
Total params: 273
Trainable params: 273
Non-trainable params: 0
_________________________________________________________________


In [86]:
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=500, batch_size=20)

Train on 404 samples, validate on 102 samples
Epoch 1/500
404/404 [==============================] - 0s 1ms/step - loss: 572.1917 - mean_absolute_error: 22.1089 - val_loss: 592.5316 - val_mean_absolute_error: 22.6067
Epoch 2/500
404/404 [==============================] - 0s 50us/step - loss: 561.8878 - mean_absolute_error: 21.8857 - val_loss: 580.5219 - val_mean_absolute_error: 22.3555
Epoch 3/500
404/404 [==============================] - 0s 65us/step - loss: 549.7944 - mean_absolute_error: 21.6202 - val_loss: 565.5464 - val_mean_absolute_error: 22.0331
Epoch 4/500
404/404 [==============================] - 0s 58us/step - loss: 534.2584 - mean_absolute_error: 21.2666 - val_loss: 547.6667 - val_mean_absolute_error: 21.6322
Epoch 5/500
404/404 [==============================] - 0s 82us/step - loss: 515.4116 - mean_absolute_error: 20.8303 - val_loss: 525.1726 - val_mean_absolute_error: 21.1279
Epoch 6/500
404/404 [==============================] - 0s 72us/step - loss: 492.3174 - mean_abs

Epoch 49/500
404/404 [==============================] - 0s 47us/step - loss: 17.1965 - mean_absolute_error: 2.8933 - val_loss: 24.4973 - val_mean_absolute_error: 3.6582
Epoch 50/500
404/404 [==============================] - 0s 42us/step - loss: 16.9405 - mean_absolute_error: 2.8591 - val_loss: 24.3548 - val_mean_absolute_error: 3.6339
Epoch 51/500
404/404 [==============================] - 0s 45us/step - loss: 16.6667 - mean_absolute_error: 2.8298 - val_loss: 24.5237 - val_mean_absolute_error: 3.6359
Epoch 52/500
404/404 [==============================] - 0s 45us/step - loss: 16.3255 - mean_absolute_error: 2.7946 - val_loss: 24.5563 - val_mean_absolute_error: 3.6025
Epoch 53/500
404/404 [==============================] - 0s 45us/step - loss: 16.0386 - mean_absolute_error: 2.7893 - val_loss: 24.9676 - val_mean_absolute_error: 3.6239
Epoch 54/500
404/404 [==============================] - 0s 42us/step - loss: 15.8410 - mean_absolute_error: 2.7654 - val_loss: 24.4886 - val_mean_absolute_

404/404 [==============================] - 0s 50us/step - loss: 10.4149 - mean_absolute_error: 2.2553 - val_loss: 22.7980 - val_mean_absolute_error: 3.0935
Epoch 97/500
404/404 [==============================] - ETA: 0s - loss: 3.4151 - mean_absolute_error: 1.548 - 0s 50us/step - loss: 10.3600 - mean_absolute_error: 2.2318 - val_loss: 22.7371 - val_mean_absolute_error: 3.0778
Epoch 98/500
404/404 [==============================] - 0s 50us/step - loss: 10.2996 - mean_absolute_error: 2.2374 - val_loss: 22.5826 - val_mean_absolute_error: 3.0766
Epoch 99/500
404/404 [==============================] - 0s 53us/step - loss: 10.1515 - mean_absolute_error: 2.2231 - val_loss: 22.9829 - val_mean_absolute_error: 3.0918
Epoch 100/500
404/404 [==============================] - 0s 47us/step - loss: 10.1910 - mean_absolute_error: 2.2392 - val_loss: 22.6685 - val_mean_absolute_error: 3.0744
Epoch 101/500
404/404 [==============================] - 0s 45us/step - loss: 10.0921 - mean_absolute_error: 2.21

Epoch 144/500
404/404 [==============================] - 0s 47us/step - loss: 8.6473 - mean_absolute_error: 2.0477 - val_loss: 20.6872 - val_mean_absolute_error: 2.8621
Epoch 145/500
404/404 [==============================] - 0s 45us/step - loss: 8.4985 - mean_absolute_error: 2.0627 - val_loss: 20.7379 - val_mean_absolute_error: 2.9104
Epoch 146/500
404/404 [==============================] - ETA: 0s - loss: 6.6963 - mean_absolute_error: 1.953 - 0s 45us/step - loss: 8.5250 - mean_absolute_error: 2.0536 - val_loss: 20.2486 - val_mean_absolute_error: 2.8486
Epoch 147/500
404/404 [==============================] - ETA: 0s - loss: 10.8394 - mean_absolute_error: 2.45 - 0s 45us/step - loss: 8.4963 - mean_absolute_error: 2.0524 - val_loss: 20.4228 - val_mean_absolute_error: 2.8568
Epoch 148/500
404/404 [==============================] - 0s 47us/step - loss: 8.5035 - mean_absolute_error: 2.0307 - val_loss: 20.4394 - val_mean_absolute_error: 2.8535
Epoch 149/500
404/404 [========================

404/404 [==============================] - 0s 45us/step - loss: 7.6679 - mean_absolute_error: 1.9510 - val_loss: 19.3238 - val_mean_absolute_error: 2.7890
Epoch 192/500
404/404 [==============================] - 0s 42us/step - loss: 7.6867 - mean_absolute_error: 1.9669 - val_loss: 19.6437 - val_mean_absolute_error: 2.8368
Epoch 193/500
404/404 [==============================] - 0s 50us/step - loss: 7.7180 - mean_absolute_error: 1.9550 - val_loss: 19.8068 - val_mean_absolute_error: 2.8465
Epoch 194/500
404/404 [==============================] - 0s 42us/step - loss: 7.6712 - mean_absolute_error: 1.9539 - val_loss: 19.0643 - val_mean_absolute_error: 2.7715
Epoch 195/500
404/404 [==============================] - 0s 45us/step - loss: 7.6564 - mean_absolute_error: 1.9465 - val_loss: 19.2427 - val_mean_absolute_error: 2.7912
Epoch 196/500
404/404 [==============================] - 0s 53us/step - loss: 7.6687 - mean_absolute_error: 1.9457 - val_loss: 19.7270 - val_mean_absolute_error: 2.8292


404/404 [==============================] - 0s 57us/step - loss: 7.0696 - mean_absolute_error: 1.8857 - val_loss: 18.4827 - val_mean_absolute_error: 2.7595
Epoch 240/500
404/404 [==============================] - 0s 52us/step - loss: 7.0972 - mean_absolute_error: 1.8761 - val_loss: 18.7113 - val_mean_absolute_error: 2.7861
Epoch 241/500
404/404 [==============================] - 0s 73us/step - loss: 7.0898 - mean_absolute_error: 1.8657 - val_loss: 18.6858 - val_mean_absolute_error: 2.7708
Epoch 242/500
404/404 [==============================] - 0s 62us/step - loss: 7.0640 - mean_absolute_error: 1.8748 - val_loss: 19.3922 - val_mean_absolute_error: 2.8531
Epoch 243/500
404/404 [==============================] - 0s 47us/step - loss: 7.0694 - mean_absolute_error: 1.8898 - val_loss: 18.6861 - val_mean_absolute_error: 2.7765
Epoch 244/500
404/404 [==============================] - 0s 47us/step - loss: 7.1200 - mean_absolute_error: 1.8855 - val_loss: 18.6307 - val_mean_absolute_error: 2.7706


404/404 [==============================] - 0s 53us/step - loss: 6.7320 - mean_absolute_error: 1.8290 - val_loss: 18.6081 - val_mean_absolute_error: 2.7843
Epoch 288/500
404/404 [==============================] - 0s 57us/step - loss: 6.7584 - mean_absolute_error: 1.8351 - val_loss: 18.6886 - val_mean_absolute_error: 2.7962
Epoch 289/500
404/404 [==============================] - 0s 45us/step - loss: 6.7361 - mean_absolute_error: 1.8303 - val_loss: 18.5421 - val_mean_absolute_error: 2.7984
Epoch 290/500
404/404 [==============================] - 0s 45us/step - loss: 6.7344 - mean_absolute_error: 1.8203 - val_loss: 18.9051 - val_mean_absolute_error: 2.8305
Epoch 291/500
404/404 [==============================] - 0s 45us/step - loss: 6.6967 - mean_absolute_error: 1.8355 - val_loss: 18.5874 - val_mean_absolute_error: 2.8071
Epoch 292/500
404/404 [==============================] - 0s 46us/step - loss: 6.7179 - mean_absolute_error: 1.8349 - val_loss: 18.7456 - val_mean_absolute_error: 2.8133


404/404 [==============================] - 0s 45us/step - loss: 6.5116 - mean_absolute_error: 1.7846 - val_loss: 18.4201 - val_mean_absolute_error: 2.7995
Epoch 336/500
404/404 [==============================] - 0s 45us/step - loss: 6.5564 - mean_absolute_error: 1.7970 - val_loss: 18.3323 - val_mean_absolute_error: 2.8006
Epoch 337/500
404/404 [==============================] - 0s 47us/step - loss: 6.4911 - mean_absolute_error: 1.8010 - val_loss: 18.3655 - val_mean_absolute_error: 2.8006
Epoch 338/500
404/404 [==============================] - 0s 47us/step - loss: 6.5043 - mean_absolute_error: 1.7977 - val_loss: 18.3871 - val_mean_absolute_error: 2.8128
Epoch 339/500
404/404 [==============================] - 0s 45us/step - loss: 6.5488 - mean_absolute_error: 1.8076 - val_loss: 18.0940 - val_mean_absolute_error: 2.7893
Epoch 340/500
404/404 [==============================] - 0s 47us/step - loss: 6.4590 - mean_absolute_error: 1.8004 - val_loss: 17.9350 - val_mean_absolute_error: 2.7686


404/404 [==============================] - 0s 46us/step - loss: 6.3656 - mean_absolute_error: 1.7876 - val_loss: 18.4904 - val_mean_absolute_error: 2.8562
Epoch 384/500
404/404 [==============================] - 0s 42us/step - loss: 6.3749 - mean_absolute_error: 1.7755 - val_loss: 18.3159 - val_mean_absolute_error: 2.8140
Epoch 385/500
404/404 [==============================] - 0s 45us/step - loss: 6.3198 - mean_absolute_error: 1.7765 - val_loss: 17.7628 - val_mean_absolute_error: 2.7734
Epoch 386/500
404/404 [==============================] - 0s 42us/step - loss: 6.3832 - mean_absolute_error: 1.7735 - val_loss: 17.9226 - val_mean_absolute_error: 2.7781
Epoch 387/500
404/404 [==============================] - 0s 45us/step - loss: 6.3468 - mean_absolute_error: 1.7721 - val_loss: 18.0860 - val_mean_absolute_error: 2.7975
Epoch 388/500
404/404 [==============================] - 0s 45us/step - loss: 6.2701 - mean_absolute_error: 1.7632 - val_loss: 19.0183 - val_mean_absolute_error: 2.8885


404/404 [==============================] - 0s 47us/step - loss: 6.2311 - mean_absolute_error: 1.7517 - val_loss: 17.8697 - val_mean_absolute_error: 2.8198
Epoch 432/500
404/404 [==============================] - 0s 48us/step - loss: 6.2598 - mean_absolute_error: 1.7673 - val_loss: 17.8424 - val_mean_absolute_error: 2.7922
Epoch 433/500
404/404 [==============================] - 0s 50us/step - loss: 6.2461 - mean_absolute_error: 1.7592 - val_loss: 17.8824 - val_mean_absolute_error: 2.8078
Epoch 434/500
404/404 [==============================] - 0s 50us/step - loss: 6.2034 - mean_absolute_error: 1.7465 - val_loss: 17.7931 - val_mean_absolute_error: 2.7966
Epoch 435/500
404/404 [==============================] - 0s 47us/step - loss: 6.1975 - mean_absolute_error: 1.7499 - val_loss: 17.9773 - val_mean_absolute_error: 2.7996
Epoch 436/500
404/404 [==============================] - 0s 52us/step - loss: 6.1981 - mean_absolute_error: 1.7469 - val_loss: 18.3415 - val_mean_absolute_error: 2.8564


404/404 [==============================] - 0s 45us/step - loss: 6.1159 - mean_absolute_error: 1.7483 - val_loss: 18.0120 - val_mean_absolute_error: 2.8293
Epoch 480/500
404/404 [==============================] - 0s 60us/step - loss: 6.1059 - mean_absolute_error: 1.7471 - val_loss: 18.0792 - val_mean_absolute_error: 2.8200
Epoch 481/500
404/404 [==============================] - 0s 57us/step - loss: 6.0873 - mean_absolute_error: 1.7436 - val_loss: 18.1690 - val_mean_absolute_error: 2.8391
Epoch 482/500
404/404 [==============================] - 0s 59us/step - loss: 6.1083 - mean_absolute_error: 1.7456 - val_loss: 18.1452 - val_mean_absolute_error: 2.8347
Epoch 483/500
404/404 [==============================] - 0s 52us/step - loss: 6.0571 - mean_absolute_error: 1.7400 - val_loss: 18.4054 - val_mean_absolute_error: 2.8482
Epoch 484/500
404/404 [==============================] - 0s 52us/step - loss: 6.1040 - mean_absolute_error: 1.7574 - val_loss: 18.1665 - val_mean_absolute_error: 2.8368


In [87]:
X_test[1], Y_test[1]

(array([-0.39242675, -0.48361547, -0.16087773, -0.25683275, -0.08840061,
        -0.49947436,  0.85606329, -0.68396235, -0.39603557,  0.15707841,
        -0.30759583,  0.42733126,  0.47880119]), 18.8)

In [88]:
X_pred = np.expand_dims(X_test[1], axis=0)
model.predict(X_pred)

array([[18.306652]], dtype=float32)