In [1]:
import keras
from keras.layers import *
from keras.optimizers import *
from keras.models import Model, Sequential
from keras.utils import np_utils
from keras.utils import plot_model

import numpy as np
import pandas as pd

import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

print(keras.__version__)
print(tf.__version__)


Using TensorFlow backend.


2.2.0
1.8.0


In [2]:
n_classes = 3

dataframe = pd.read_csv('../../input/iris.csv', header=1)
dataset = dataframe.values

X = dataset[:,0:4].astype(float)
Y = dataset[:,4]
print(X.shape, Y.shape)

dataframe.head()

(149, 4) (149,)


5.1  3.5  1.4  0.2  setosa
0  4.9  3.0  1.4  0.2  setosa
1  4.7  3.2  1.3  0.2  setosa
2  4.6  3.1  1.5  0.2  setosa
3  5.0  3.6  1.4  0.2  setosa
4  5.4  3.9  1.7  0.4  setosa

In [3]:
# Encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
Y = np_utils.to_categorical(encoded_Y)
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [4]:
# Partition
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size = 0.1, random_state = 7)
X_train, X_test, Y_train, Y_test = train_test_split(X_train, Y_train, test_size = 0.1, random_state = 7)

print(X_train.shape, X_val.shape, X_test.shape)

(120, 4) (15, 4) (14, 4)


In [5]:
# Create model
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

# Save model image
plot_model(model, to_file='classification-iris.png')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=500, batch_size=5)

Train on 120 samples, validate on 15 samples
Epoch 1/500
120/120 [==============================] - 0s 159us/step - loss: 0.0808 - acc: 0.9667 - val_loss: 0.0470 - val_acc: 1.0000
Epoch 2/500
120/120 [==============================] - 0s 213us/step - loss: 0.0824 - acc: 0.9667 - val_loss: 0.0467 - val_acc: 1.0000
Epoch 3/500
120/120 [==============================] - 0s 215us/step - loss: 0.0789 - acc: 0.9667 - val_loss: 0.0589 - val_acc: 1.0000
Epoch 4/500
120/120 [==============================] - 0s 201us/step - loss: 0.0807 - acc: 0.9750 - val_loss: 0.0467 - val_acc: 1.0000
Epoch 5/500
120/120 [==============================] - 0s 167us/step - loss: 0.0794 - acc: 0.9667 - val_loss: 0.0478 - val_acc: 1.0000
Epoch 6/500
120/120 [==============================] - 0s 226us/step - loss: 0.0796 - acc: 0.9750 - val_loss: 0.0494 - val_acc: 1.0000
Epoch 7/500
120/120 [==============================] - 0s 170us/step - loss: 0.0786 - acc: 0.9583 - val_loss: 0.0461 - val_acc: 1.0000
Epoch 8/50

120/120 [==============================] - 0s 142us/step - loss: 0.0811 - acc: 0.9583 - val_loss: 0.0396 - val_acc: 1.0000
Epoch 61/500
120/120 [==============================] - 0s 150us/step - loss: 0.0782 - acc: 0.9583 - val_loss: 0.0370 - val_acc: 1.0000
Epoch 62/500
120/120 [==============================] - 0s 142us/step - loss: 0.0711 - acc: 0.9833 - val_loss: 0.0341 - val_acc: 1.0000
Epoch 63/500
120/120 [==============================] - 0s 125us/step - loss: 0.0798 - acc: 0.9583 - val_loss: 0.0500 - val_acc: 1.0000
Epoch 64/500
120/120 [==============================] - 0s 150us/step - loss: 0.0770 - acc: 0.9833 - val_loss: 0.0342 - val_acc: 1.0000
Epoch 65/500
120/120 [==============================] - 0s 155us/step - loss: 0.0749 - acc: 0.9750 - val_loss: 0.0360 - val_acc: 1.0000
Epoch 66/500
120/120 [==============================] - 0s 153us/step - loss: 0.0788 - acc: 0.9667 - val_loss: 0.0325 - val_acc: 1.0000
Epoch 67/500
120/120 [==============================] - 0s 16

120/120 [==============================] - 0s 134us/step - loss: 0.0668 - acc: 0.9750 - val_loss: 0.0259 - val_acc: 1.0000
Epoch 121/500
120/120 [==============================] - 0s 130us/step - loss: 0.0709 - acc: 0.9667 - val_loss: 0.0319 - val_acc: 1.0000
Epoch 122/500
120/120 [==============================] - 0s 134us/step - loss: 0.0721 - acc: 0.9750 - val_loss: 0.0335 - val_acc: 1.0000
Epoch 123/500
120/120 [==============================] - 0s 134us/step - loss: 0.0679 - acc: 0.9667 - val_loss: 0.0246 - val_acc: 1.0000
Epoch 124/500
120/120 [==============================] - 0s 134us/step - loss: 0.0703 - acc: 0.9833 - val_loss: 0.0246 - val_acc: 1.0000
Epoch 125/500
120/120 [==============================] - 0s 134us/step - loss: 0.0734 - acc: 0.9583 - val_loss: 0.0320 - val_acc: 1.0000
Epoch 126/500
120/120 [==============================] - 0s 134us/step - loss: 0.0672 - acc: 0.9667 - val_loss: 0.0242 - val_acc: 1.0000
Epoch 127/500
120/120 [==============================] 

120/120 [==============================] - 0s 134us/step - loss: 0.0712 - acc: 0.9667 - val_loss: 0.0275 - val_acc: 1.0000
Epoch 180/500
120/120 [==============================] - 0s 134us/step - loss: 0.0648 - acc: 0.9667 - val_loss: 0.0201 - val_acc: 1.0000
Epoch 181/500
120/120 [==============================] - 0s 134us/step - loss: 0.0665 - acc: 0.9667 - val_loss: 0.0254 - val_acc: 1.0000
Epoch 182/500
120/120 [==============================] - 0s 142us/step - loss: 0.0653 - acc: 0.9750 - val_loss: 0.0191 - val_acc: 1.0000
Epoch 183/500
120/120 [==============================] - 0s 136us/step - loss: 0.0733 - acc: 0.9833 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 184/500
120/120 [==============================] - 0s 167us/step - loss: 0.0659 - acc: 0.9667 - val_loss: 0.0226 - val_acc: 1.0000
Epoch 185/500
120/120 [==============================] - 0s 159us/step - loss: 0.0677 - acc: 0.9833 - val_loss: 0.0229 - val_acc: 1.0000
Epoch 186/500
120/120 [==============================] 

120/120 [==============================] - 0s 125us/step - loss: 0.0667 - acc: 0.9833 - val_loss: 0.0181 - val_acc: 1.0000
Epoch 239/500
120/120 [==============================] - 0s 184us/step - loss: 0.0632 - acc: 0.9667 - val_loss: 0.0202 - val_acc: 1.0000
Epoch 240/500
120/120 [==============================] - 0s 167us/step - loss: 0.0655 - acc: 0.9833 - val_loss: 0.0245 - val_acc: 1.0000
Epoch 241/500
120/120 [==============================] - 0s 134us/step - loss: 0.0644 - acc: 0.9833 - val_loss: 0.0166 - val_acc: 1.0000
Epoch 242/500
120/120 [==============================] - 0s 134us/step - loss: 0.0709 - acc: 0.9667 - val_loss: 0.0172 - val_acc: 1.0000
Epoch 243/500
120/120 [==============================] - 0s 134us/step - loss: 0.0680 - acc: 0.9750 - val_loss: 0.0200 - val_acc: 1.0000
Epoch 244/500
120/120 [==============================] - 0s 134us/step - loss: 0.0647 - acc: 0.9750 - val_loss: 0.0180 - val_acc: 1.0000
Epoch 245/500
120/120 [==============================] 

Epoch 298/500
120/120 [==============================] - 0s 159us/step - loss: 0.0660 - acc: 0.9667 - val_loss: 0.0142 - val_acc: 1.0000
Epoch 299/500
120/120 [==============================] - 0s 155us/step - loss: 0.0744 - acc: 0.9750 - val_loss: 0.0140 - val_acc: 1.0000
Epoch 300/500
120/120 [==============================] - 0s 138us/step - loss: 0.0625 - acc: 0.9750 - val_loss: 0.0155 - val_acc: 1.0000
Epoch 301/500
120/120 [==============================] - 0s 134us/step - loss: 0.0610 - acc: 0.9833 - val_loss: 0.0178 - val_acc: 1.0000
Epoch 302/500
120/120 [==============================] - 0s 134us/step - loss: 0.0691 - acc: 0.9667 - val_loss: 0.0200 - val_acc: 1.0000
Epoch 303/500
120/120 [==============================] - 0s 150us/step - loss: 0.0664 - acc: 0.9833 - val_loss: 0.0207 - val_acc: 1.0000
Epoch 304/500
120/120 [==============================] - 0s 155us/step - loss: 0.0692 - acc: 0.9667 - val_loss: 0.0195 - val_acc: 1.0000
Epoch 305/500
120/120 [==================

Epoch 358/500
120/120 [==============================] - 0s 159us/step - loss: 0.0693 - acc: 0.9750 - val_loss: 0.0137 - val_acc: 1.0000
Epoch 359/500
120/120 [==============================] - 0s 184us/step - loss: 0.0615 - acc: 0.9750 - val_loss: 0.0151 - val_acc: 1.0000
Epoch 360/500
120/120 [==============================] - 0s 180us/step - loss: 0.0612 - acc: 0.9833 - val_loss: 0.0161 - val_acc: 1.0000
Epoch 361/500
120/120 [==============================] - 0s 159us/step - loss: 0.0617 - acc: 0.9750 - val_loss: 0.0133 - val_acc: 1.0000
Epoch 362/500
120/120 [==============================] - 0s 159us/step - loss: 0.0643 - acc: 0.9833 - val_loss: 0.0146 - val_acc: 1.0000
Epoch 363/500
120/120 [==============================] - 0s 159us/step - loss: 0.0588 - acc: 0.9750 - val_loss: 0.0146 - val_acc: 1.0000
Epoch 364/500
120/120 [==============================] - 0s 167us/step - loss: 0.0617 - acc: 0.9750 - val_loss: 0.0155 - val_acc: 1.0000
Epoch 365/500
120/120 [==================

Epoch 418/500
120/120 [==============================] - 0s 159us/step - loss: 0.0616 - acc: 0.9833 - val_loss: 0.0131 - val_acc: 1.0000
Epoch 419/500
120/120 [==============================] - 0s 209us/step - loss: 0.0671 - acc: 0.9667 - val_loss: 0.0142 - val_acc: 1.0000
Epoch 420/500
120/120 [==============================] - 0s 167us/step - loss: 0.0818 - acc: 0.9583 - val_loss: 0.0114 - val_acc: 1.0000
Epoch 421/500
120/120 [==============================] - 0s 142us/step - loss: 0.0572 - acc: 0.9833 - val_loss: 0.0177 - val_acc: 1.0000
Epoch 422/500
120/120 [==============================] - 0s 142us/step - loss: 0.0658 - acc: 0.9750 - val_loss: 0.0120 - val_acc: 1.0000
Epoch 423/500
120/120 [==============================] - 0s 142us/step - loss: 0.0623 - acc: 0.9833 - val_loss: 0.0189 - val_acc: 1.0000
Epoch 424/500
120/120 [==============================] - 0s 142us/step - loss: 0.0586 - acc: 0.9750 - val_loss: 0.0125 - val_acc: 1.0000
Epoch 425/500
120/120 [==================

120/120 [==============================] - 0s 150us/step - loss: 0.0668 - acc: 0.9667 - val_loss: 0.0116 - val_acc: 1.0000
Epoch 478/500
120/120 [==============================] - 0s 150us/step - loss: 0.0600 - acc: 0.9750 - val_loss: 0.0118 - val_acc: 1.0000
Epoch 479/500
120/120 [==============================] - 0s 153us/step - loss: 0.0622 - acc: 0.9833 - val_loss: 0.0208 - val_acc: 1.0000
Epoch 480/500
120/120 [==============================] - 0s 134us/step - loss: 0.0604 - acc: 0.9833 - val_loss: 0.0116 - val_acc: 1.0000
Epoch 481/500
120/120 [==============================] - 0s 142us/step - loss: 0.0636 - acc: 0.9833 - val_loss: 0.0140 - val_acc: 1.0000
Epoch 482/500
120/120 [==============================] - 0s 150us/step - loss: 0.0631 - acc: 0.9750 - val_loss: 0.0129 - val_acc: 1.0000
Epoch 483/500
120/120 [==============================] - 0s 159us/step - loss: 0.0617 - acc: 0.9833 - val_loss: 0.0155 - val_acc: 1.0000
Epoch 484/500
120/120 [==============================] 

In [7]:
model.evaluate(X_test, Y_test, verbose=1)

14/14 [==============================] - 0s 72us/step


[0.025591786950826645, 1.0]

In [8]:
predictions = model.predict(X_test)
predictions

array([[9.98159826e-01, 1.84021762e-03, 1.12112479e-12],
       [3.80176614e-04, 9.96437192e-01, 3.18255136e-03],
       [2.13932269e-03, 9.91174221e-01, 6.68644859e-03],
       [4.28692947e-05, 9.29951310e-01, 7.00058043e-02],
       [9.03646927e-04, 9.92909431e-01, 6.18701009e-03],
       [1.09357750e-07, 6.88378140e-02, 9.31162059e-01],
       [2.67105662e-08, 1.48356836e-02, 9.85164285e-01],
       [5.06509654e-03, 9.92887318e-01, 2.04762677e-03],
       [1.50062406e-04, 9.66039598e-01, 3.38102989e-02],
       [9.98261869e-01, 1.73818821e-03, 1.45649833e-12],
       [1.25598302e-03, 9.95260060e-01, 3.48395901e-03],
       [9.24398191e-04, 9.55868006e-01, 4.32076529e-02],
       [9.99236703e-01, 7.63288641e-04, 9.51455440e-14],
       [1.02422644e-04, 9.19502258e-01, 8.03954005e-02]], dtype=float32)

In [9]:
np.argmax(predictions, axis=1)

array([0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 0, 1], dtype=int64)

In [10]:
Y_test

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [11]:
# serialize model to JSON
model_json = model.to_json()
with open("classification-iris.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("classification-iris.h5")